### ISSUE TITLE
Log configured timeout for context deadline exceeded

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/notifiarr#332]
```
Getting Radarr Queue from 1:http://127.0.0.1:7878/radarr: getting movies from instance 1: api.Get(v3/movie): httpClient.Do(req): Get "http://127.0.0.1:7878/radarr/api/v3/movie": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

add what the Client.Timeout is

**Comment by davidnewhall** [comment]
It's logged on startup. It's not always known at time of actual timeout.

**Comment by davidnewhall** [comment]
I looked into this more, and it's just not a feasible change right now. All of the error print messages for every app are scattered all over the code. And instead of print the error, I would have to test for which error it is, and then append the timeout value you configured for the app to the message in the case of a timeout. It's a lot of extra code, a lot of potential for typos and bugs, and not really worth it at the moment. All of the timeouts are printed on startup. You can also extrapolate the timeout from the different between the timestamp on the debug message and the time stamp on the error message that indicated a timeout occurred.

**Comment by davidnewhall** [comment]
I will look into ways to implement something like this at a lower level, but it's not a priority.
