### ISSUE TITLE
[Feature Request] [Enhancement] Request individual seasons, *arr API optimization

### ISSUE THREAD

**Issue by micle546** [Notifiarr/notifiarr#392]
Two things:

1
It seems like the *arr api (sonarr specifically) calls to check if an item already exists occur in the search window, which results in a query to each individual search result (slow, if it's making an api call for each search result, which I'm guessing is what's happening)

Instead, I sugest the api call be moved to the 'cart' page, where there 'should' be less api calls to make per search per user visit, improving processing times for this feature. This could probably be similarly applied to the other *arr api calls, with some more thought.

Example UI change:
![image](https://user-images.githubusercontent.com/1088521/209867274-2c83959d-659b-46d4-82c3-6624c4fcb655.png)
using
`http://<IPADDRESS>:8989/api/v3/series/<ID>?apikey=<APIKEY>`
and parsing for either the ID to see if it's added to sonarr, setting the monitored flag for the series to enable tracking for the seasons, and using the monitored flag per season to see if each season has been 'requested' if it is monitored, disable the option in that select statement, to prevent multiple requests.

2
Reason being:
I'd like my users to have to request individual (specific) seasons of a show instead of the current options (all, latest, none (WHY?), future), I would prefer to be able to disable the 'all' option, too (this might be a thing, I'm tired)

I'm coming from the now archived https://github.com/darkalfx/requestrr which had the option to request individual seasons, might be able to take a look there to see how they did it

**Comment by austinwbest** [comment]
1. There is an option to precheck existing and it does it in the page it currently happens on so people don't add things that are already added. Yes, sonarr v3 with mono is slow AF which is why I don't even use that for sonarr. V4 should be much faster with that.

2. Specific season picking is on the list, just have not got to it quite yet. Not heavily requested. 

Side note, why none? No clue, I just used what sonarr has native.

Feel free to jump on discord if you want to discuss things further

**Comment by micle546** [comment]
closing, reopening in discord for discussion
