### ISSUE TITLE
Run Windows notifiarr client in background

### ISSUE THREAD

**Issue by kyleyee52** [Notifiarr/notifiarr#649]
I would like to run the client purely in the background.

Upon startup, it just makes a terminal window but I would like to have it run entirely from the tray instead. 

I've tried using both nssm and Task Scheduler to try and achieve this effect but the client doesn't start.

**Comment by davidnewhall** [comment]
It's giving you a window because Windows has switched to a new "Terminal" and things are a bit different. 
See the [Windows installation instructions](https://notifiarr.wiki/en/Client/Installation#windows-startup) for a description of host to use `conhost.exe` to make the Terminal window go away. I'll remove the console window entirely in the next release.

**Comment by davidnewhall** [comment]
To use nssm, you need to pass `USEGUI=false` as an environment variable. This will disable the system tray and allow the app to run purely in the background as a system service.

**Comment by davidnewhall** [comment]
Did you have any questions?
