### ISSUE TITLE
v0.8.1 will not update on Windows 11

### ISSUE THREAD

**Issue by PicantePeperoni** [Notifiarr/notifiarr#791]
Hello,
During the update process, I am receiving the following error message.
![image](https://github.com/user-attachments/assets/53868d0e-7ea7-48b1-aa38-831809c1e9b6)

![image](https://github.com/user-attachments/assets/b473cbe0-8ad4-4ddc-9d6f-282625d41cb5)

Thank you,

**Comment by davidnewhall** [comment]
Thanks for the report!

I managed to break this. It's trying to execute the zip file instead of extracting the exe from it. It'll be fixed in 0.8.2, but that means it won't work for you until I release a version greater than 0.8.2. In other words, you'll need to manually update to 0.8.1 and to 0.8.2, then it'll work.
