### ISSUE TITLE
Add queue support to client

### ISSUE THREAD

**Issue by austinwbest** [Notifiarr/notifiarr#86]
So to track/notify stalled imports, lets add this.

Monitor the queue every 5 mins, if an item has been finished for more than 10 minutes we need to post that to the site. I'll make an endpoint to accept it

Endpoint: `/api/v1/user/client`
Method: POST
Payload: `{type: 'queue', app: 'radarr', download_id: '....', title: '....', release: '....', finished: '....', message: '....'}`

An example, adjust as needed as nothing is in place on my end other than checking the type

**Comment by bakerboy448** [comment]
Is it possible to grab the message from queue (if it exists)?

**Comment by davidnewhall** [comment]
Yes.

**Comment by davidnewhall** [comment]
I've put some thought into this. The more I think about it the less I like the idea of this being in Unpackerr. I also don't like the idea of (1) sending you "stuck items" every 5 minutes, but that approach seems almost appropriate. The other option is that (2) the client tracks the items in each app's queue. The client could be configurable to send 1 POST (notification) when an item has been stuck for N minutes.

Both approaches allow folks to get 1 notification, or configure it to get 1 every N minutes until they fix the problem. In approach (1) you'd have to track the downloads on your end if they chose only 1 notification per "stuck item."  In the approach (2) the client tracks the items if they select that option.

Notes/Question:
- How do we report back to notifiarr.com that the problem is fixed (so you can remove the tracking record)? Maybe we don't need to, and you can just time it out after 24 hours of not being sent.
- AFAICT, the queues do not include how long it's been finished. I can see if it is finished, and I can see if it has status messages (errors).

Let me know your thoughts. It'd be really easy for  to slap together a timer to poll each app every 5 minutes, and send you a list of completed/stuck/error'd queue items for each configured app. A little less easy to track them, but one of us has to deal with that. I like the idea of the site doing it because it's more stateful and will live through a client restart.
